all:
	g++ -o visualTracking main.cpp utils.cpp ControlPoint.cpp Capsule.cpp VideoManager.cpp PointCloudManager.cpp -lopencv_features2d -lopencv_nonfree -lopencv_highgui -lopencv_video -lopencv_calib3d -lopencv_core -lopencv_flann -lopencv_imgproc -lboost_system -lboost_serialization -I/usr/include/eigen3 -I/usr/include/pcl-1.7/ -L/usr/lib -lpcl_io -lpcl_common -lpcl_surface -lpcl_kdtree -lpcl_search -lpcl_features -lpcl_filters

